import type { SelectedMetrics } from '@/types/cvss'

export const metricOrderV4_0 = [
  'AV',
  'AC',
  'AT',
  'PR',
  'UI',
  'VC',
  'VI',
  'VA',
  'SC',
  'SI',
  'SA',
  'E',
  'CR',
  'IR',
  'AR',
  'MAV',
  'MAC',
  'MAT',
  'MPR',
  'MUI',
  'MVC',
  'MVI',
  'MVA',
  'MSC',
  'MSI',
  'MSA',
  'S',
  'AU',
  'R',
  'V',
  'RE',
  'U',
]

export const defaultMetricsV4_0: SelectedMetrics = {
  AV: 'N',
  AC: 'L',
  AT: 'N',
  PR: 'N',
  UI: 'N',
  VC: 'H',
  VI: 'H',
  VA: 'H',
  SC: 'N',
  SI: 'N',
  SA: 'N',
  E: 'X',
  CR: 'X',
  IR: 'X',
  AR: 'X',
  MAV: 'X',
  MAC: 'X',
  MAT: 'X',
  MPR: 'X',
  MUI: 'X',
  MVC: 'X',
  MVI: 'X',
  MVA: 'X',
  MSC: 'X',
  MSI: 'X',
  MSA: 'X',
  S: 'X',
  AU: 'X',
  R: 'X',
  V: 'X',
  RE: 'X',
  U: 'X',
}

export const metricGroupsV4_0: Record<string, string[]> = {
  'Base Metrics - Exploitability': ['AV', 'AC', 'AT', 'PR', 'UI'],
  'Base Metrics - Vulnerable System Impact': ['VC', 'VI', 'VA'],
  'Base Metrics - Subsequent System Impact': ['SC', 'SI', 'SA'],
  'Threat Metrics': ['E'],
  'Environmental Metrics - Security Requirements': ['CR', 'IR', 'AR'],
  'Environmental Metrics - Modified Base': [
    'MAV',
    'MAC',
    'MAT',
    'MPR',
    'MUI',
    'MVC',
    'MVI',
    'MVA',
    'MSC',
    'MSI',
    'MSA',
  ],
  'Supplemental Metrics': ['S', 'AU', 'R', 'V', 'RE', 'U'],
}

export const metricOrderV3_1 = [
  'AV',
  'AC',
  'PR',
  'UI',
  'S',
  'C',
  'I',
  'A',
  'E',
  'RL',
  'RC',
  'CR',
  'IR',
  'AR',
  'MAV',
  'MAC',
  'MPR',
  'MUI',
  'MS',
  'MC',
  'MI',
  'MA',
]

export const defaultMetricsV3_1: SelectedMetrics = {
  AV: 'N',
  AC: 'L',
  PR: 'N',
  UI: 'N',
  S: 'U',
  C: 'N',
  I: 'N',
  A: 'N',
  E: 'X',
  RL: 'X',
  RC: 'X',
  CR: 'X',
  IR: 'X',
  AR: 'X',
  MAV: 'X',
  MAC: 'X',
  MPR: 'X',
  MUI: 'X',
  MS: 'X',
  MC: 'X',
  MI: 'X',
  MA: 'X',
}

export const metricGroupsV3_1: Record<string, string[]> = {
  'Base Metrics - Exploitability': ['AV', 'AC', 'PR', 'UI'],
  'Base Metrics - Impact': ['S', 'C', 'I', 'A'],
  'Temporal Metrics': ['E', 'RL', 'RC'],
  'Environmental Metrics - Security Requirements': ['CR', 'IR', 'AR'],
  'Environmental Metrics - Modified Base': ['MAV', 'MAC', 'MPR', 'MUI', 'MS', 'MC', 'MI', 'MA'],
}
