import type { SelectedMetrics } from '@/types/cvss'

export const metricOrderV4_0 = [
  'AV',
  'AC',
  'AT',
  'PR',
  'UI',
  'VC',
  'VI',
  'VA',
  'SC',
  'SI',
  'SA',
  'E',
  'CR',
  'IR',
  'AR',
  'MAV',
  'MAC',
  'MAT',
  'MPR',
  'MUI',
  'MVC',
  'MVI',
  'MVA',
  'MSC',
  'MSI',
  'MSA',
  'S',
  'AU',
  'R',
  'V',
  'RE',
  'U',
]

export const defaultMetricsV4_0: SelectedMetrics = {
  AV: 'N',
  AC: 'L',
  AT: 'N',
  PR: 'N',
  UI: 'N',
  VC: 'N',
  VI: 'N',
  VA: 'N',
  SC: 'N',
  SI: 'N',
  SA: 'N',
  E: 'X',
  CR: 'X',
  IR: 'X',
  AR: 'X',
  MAV: 'X',
  MAC: 'X',
  MAT: 'X',
  MPR: 'X',
  MUI: 'X',
  MVC: 'X',
  MVI: 'X',
  MVA: 'X',
  MSC: 'X',
  MSI: 'X',
  MSA: 'X',
  S: 'X',
  AU: 'X',
  R: 'X',
  V: 'X',
  RE: 'X',
  U: 'X',
}

export const metricGroupsV4_0: Record<string, string[]> = {
  'Base Metrics': [],
  'Exploitability Metrics': ['AV', 'AC', 'AT', 'PR', 'UI'],
  'Vulnerable System Impact Metrics': ['VC', 'VI', 'VA'],
  'Subsequent System Impact Metrics': ['SC', 'SI', 'SA'],
  'Supplemental Metrics': ['S', 'AU', 'R', 'V', 'RE', 'U'],
  'Environmental (Modified Base Metrics)': [],
  'Modified Exploitability Metrics': ['MAV', 'MAC', 'MAT', 'MPR', 'MUI'],
  'Modified Vulnerable System Impact Metrics': ['MVC', 'MVI', 'MVA'],
  'Modified Subsequent System Impact Metrics': ['MSC', 'MSI', 'MSA'],
  'Environmental (Security Requirements)': ['CR', 'IR', 'AR'],
  'Threat Metrics': ['E'],
}

export const metricOrderV3_1 = [
  'AV',
  'AC',
  'PR',
  'UI',
  'S',
  'C',
  'I',
  'A',
  'E',
  'RL',
  'RC',
  'CR',
  'IR',
  'AR',
  'MAV',
  'MAC',
  'MPR',
  'MUI',
  'MS',
  'MC',
  'MI',
  'MA',
]

export const defaultMetricsV3_1: SelectedMetrics = {
  AV: 'N',
  AC: 'L',
  PR: 'N',
  UI: 'N',
  S: 'U',
  C: 'N',
  I: 'N',
  A: 'N',
  E: 'X',
  RL: 'X',
  RC: 'X',
  CR: 'X',
  IR: 'X',
  AR: 'X',
  MAV: 'X',
  MAC: 'X',
  MPR: 'X',
  MUI: 'X',
  MS: 'X',
  MC: 'X',
  MI: 'X',
  MA: 'X',
}

export const metricGroupsV3_1: Record<string, string[]> = {
  'Base Score': ['AV', 'AC', 'PR', 'UI', 'S', 'C', 'I', 'A'],
  'Temporal Score': ['E', 'RL', 'RC'],
  'Environmental Score': ['CR', 'IR', 'AR', 'MAV', 'MAC', 'MPR', 'MUI', 'MS', 'MC', 'MI', 'MA'],
}
